id: AFA422EFE
base_file: f638B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-31 05:13:14.149600
  last_modified_at: 2022-05-31 05:13:14.149607
